### ISSUE TITLE
question for how to classify which of a dialogue pair is more preferred. 

### ISSUE THREAD

**Issue by JianqiaoLu** [lhao499/CoH#11]
I noticed that you provide a figure 3 in the pdf, shown the comparison about for the accuracy of
classifying the preferred dialogue on the dataset.

I want to know how the trained model do this classifying? do you add a value layer to the LM or something else?

**Comment by keezen** [comment]
I have the same question? Have you figure it out, bro?

**Comment by JianqiaoLu** [comment]
> I have the same question? Have you figure it out, bro?

you can just concatenate the prompts + {good example}/{bad example} to the model, compare the sum of log probability of predicting the good example/bad example, to show your model preference.
