### ISSUE TITLE
Reproduce CoH on alpaca

### ISSUE THREAD

**Issue by Guochry** [lhao499/CoH#15]
Thanks for this great work first! And I am trying to reproduce CoH on alpaca model, so if it is necessary for me to have the access to the Jax weight of alpaca first?

**Comment by haoliuhl** [comment]
You will need an initial model to begin with, e.g. a LLaMA or alpaca model.

For training CoH using this Jax codebase, you can use [coh/scripts/convert_checkpoint.py](https://github.com/lhao499/chain-of-hindsight/blob/main/coh/scripts/convert_checkpoint.py) to convert PyTorch weights to Jax format. 

If you would like to use PyTorch training codebase (e.g. FastChat), you can use [coh/data/pack_hf.py](https://github.com/lhao499/chain-of-hindsight/blob/main/coh/data/pack_hf.py) to pack human feedback data into CoH format.
