### ISSUE TITLE
generated data

### ISSUE THREAD

**Issue by skepsun** [lhao499/CoH#16]
is it proper?
<img width="424" alt="image" src="https://github.com/lhao499/chain-of-hindsight/assets/27009335/a5f7fcd8-248d-4da6-8ce4-cd0a64680461">

**Comment by skepsun** [comment]
The logic and code for preprocessing dataset are too complicated and redundant

**Comment by haoliuhl** [comment]
@skepsun I've added documentation for explanting the data preprocessing: [data doc](https://github.com/lhao499/chain-of-hindsight/blob/main/coh/data/doc.md), hope it helps. The design is for maximum flexibility when handling multi-turn conversations.
