### ISSUE TITLE
Usage of the 'masks' in hf_data

### ISSUE THREAD

**Issue by g131002** [lhao499/CoH#5]
I thought the 'masks' part yielded by hf_data
https://github.com/lhao499/CoH/blob/3949417c638834d9213f6395196db1a802e61d8c/coh/data/hf_data.py#L68 
is to take care of the indicator function in the paper.
![image](https://user-images.githubusercontent.com/21119354/225884764-87a9d1aa-5a64-4f19-9d43-c21f823ed622.png)
However, I couldn't find the place where the 'masks' part is used in the code. Does this mean that you actually not used the indicator function? Or if I missed something, could you please correct me?

**Comment by haoliuhl** [comment]
Thanks for catching this, we made an mistake while releasing it, pushed an update.

**Comment by g131002** [comment]
Thank you for the quick fix!
So you actually used 'masks' part in the experiment, right?
Also, I checked the part of the code where you fixed, and don't you also have to take care of the bos_token part?
And about the bos_token part, did you also append the bos_token when you did the evaluation?

**Comment by haoliuhl** [comment]
Yeah, using masks is important, otherwise model will generate 'user' part which is undesired.

**Comment by haoliuhl** [comment]
bos_token is for input, loss_mask will take care of output and loss. bos_token is not used in evaluation because we have question/instruction as input and not doing unconditional generation.
