### ISSUE TITLE
About CoH evaluation

### ISSUE THREAD

**Issue by YinminZhang** [lhao499/CoH#6]
First of all, I sincerely the author for this meaningful work. I have encountered several issues while testing the CoH and would appreciate some guidance:

1. It seems that the following section of code causes the config not to work as expected:
https://github.com/lhao499/CoH/blob/73adce65b857326258380e3c2d440d93ad50ad74/coh/scripts/lm_serve.py#L31-L48

2. In the train code, the save_checkpoint function does not save `trainstate_params` used in load_checkpoint:
https://github.com/lhao499/CoH/blob/73adce65b857326258380e3c2d440d93ad50ad74/coh/coh_train.py#L200-L212

3. There might be an issue with the`input_shape` during the model initialization:
https://github.com/lhao499/CoH/blob/73adce65b857326258380e3c2d440d93ad50ad74/coh/scripts/lm_serve.py#L73-L78

Could you please help me address these issues? Thank you!

**Comment by haoliuhl** [comment]
Apologize for the delay, these issues should be addressed in recent updates. Let me know if it still happens.
